name: "Chore"
description: "Open a Chore for minor update."
labels: "type : chore"
title: "🧹 chore: "
body:
  - type: markdown
    attributes:
      value: "Whistle while you work!"

  - type: textarea
    id: goal
    attributes:
      label: What is the goal of this chore?
      description: Describe the update details and why it's needed. 
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      description: Explain what will be updated.
    validations:
      required: true
