name: 📖 Documentation
description: Update documentation
labels: [area/documentation]
body:
  - type: markdown
    attributes:
      value: |
        This template is strictly used for documentation requests, including:

        - Documenting undocumented APIs;
        - Elaborating on a particular topic;
        - Providing charts or diagrams;
        - anything else that doesn't require code changes.

        If you followed the documentation but things don't work, was it the docs or the code?
        If the code was wrong, please file a bug report instead.

        Before you go ahead, please check if this documentation issue has [already been reported](./).
  - type: textarea
    attributes:
      label: What needs to be documented?
      description: Provide a description for the purpose of these docs.
    validations:
      required: true
