name: ✨ Feature Request
description: Propose a new feature
labels: [Enhancement]
title: "✨: "
body:
  - type: markdown
    attributes:
      value: |
        Please check if this feature request has [already been filed](./).
  - type: textarea
    id: goal
    attributes:
      label: What is being accomplished?
      description: Describe the purpose of the enhancement.
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Provide steps for implementation.
    validations:
      requirements: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List necessary factors or materials to achieve this goal.
  - type: textarea
    id: additional
    attributes:
      label: Additional Details
      description: Screenshots, links etc.
    validations:
      required: false
