name: ✨ Feature Request
description: Propose a new feature
labels: [Enhancement]
title: "✨: "
body:
  - type: markdown
    attributes:
      value: |
        Please check if this feature request has [already been filed](./).
  - type: textarea
    id: goal
    attributes:
      label: What is being accomplished?
      description: Describe the purpose of the enhancement.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        #### Add Labels
        ##### Provide status with semantic labelling. 👉
          **Severity**  
          &nbsp;&nbsp;&nbsp;&nbsp;- `Low Priority`
          &nbsp;&nbsp;&nbsp;&nbsp;- `Medium Priority`
          &nbsp;&nbsp;&nbsp;&nbsp;- `High Priority`
          **Time Demand**  
          &nbsp;&nbsp;&nbsp;&nbsp;- `Quick Fix`
          &nbsp;&nbsp;&nbsp;&nbsp;- `Long-Term`
          **Feature** (*optional*)
          &nbsp;&nbsp;&nbsp;&nbsp;- e.g. Arsenal, Fortify, Canvassing, etc.
    validations:
      required: true
  - type: textarea
    id: Implementation
    attributes:
      label: Implementation
      description: Explain how this enhancement will be completed.
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Provide necessary steps to achieve this goal.
    validations:
      requirements: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List necessary factors or materials to achieve this goal.
  - type: textarea
    id: additional
    attributes:
      label: Additional Details
      description: Provide further context.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots, Links, Etc.
      description: Drag and Drop Images or Paste Link.
    validations:
      required: false
