name: 🏗️ Refactor Request
description: Suggest a refactor
labels: [Refactor]
title: "refactor: "
body:
  - type: markdown
    attributes:
      value: |
        Please check if this refactor request has [already been filed](./).
  - type: textarea
    id: goal
    attributes:
      label: What needs to be refactored?
      description: Describe the purpose of the refactor.
    validations:
      required: true
  - type: textarea
    id: Implementation
    attributes:
      label: Implementation
      description: Explain what will be updated.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Details
      description: Screenshots, Links, Etc.
    validations:
      required: false
