name: 🧪 Testing Support
description: Propose new tests
labels: [Testing]
title: "🧪: "
body:
  - type: markdown
    attributes:
      value: |
        Please check if this testing request has [already been filed](./).
  - type: textarea
    id: goal
    attributes:
      label: What is being tested?
      description: Describe the purpose of the tests.
    validations:
      required: true
  - type: textarea
    id: Implementation
    attributes:
      label: Implementation
      description: Explain how these tests will be executed.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Details
      description: Screenshots, links, etc.
    validations:
      required: false
